[package]
name = "src"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = "0.14.0"
iced_aw = { version = "0.13.0", features = ["full"] }
iced_fonts = { version = "0.3.0", features = ["full"] }
